CREATE TABLE `marm_nltracking` (
`OXID` CHAR( 32 ) NOT NULL ,
`MARMUSERID` CHAR( 32 ) NOT NULL ,
`MARMNLID` CHAR( 32 ) NOT NULL ,
`MARMNLSEND` TINYINT( 1 ) NOT NULL ,
PRIMARY KEY ( `OXID` )
) ENGINE = MYISAM 